
# a target to build an executable file from source files with c++17 standart
# the target project_x has a dependicy : main.o
# it means, firstly : execute the target "main.o"

#Linking stage (object files to executable)
build/File_Io: build/File_Io.o
	g++ -std=c++17 -o build/File_Io build/File_Io.o

# Compiling stage (source files to object files)
build/File_Io.o: File_Io.cpp
	g++ -std=c++17 -c -o build/File_Io.o File_Io.cpp

#cleaning upp    
clean:
	rm --force build/File_Io build/File_Io.o


#we define our default target
default: build/File_Io 


.PHONY: build/File_io
