name: Build and Test "CAN_Messages" Component

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    name: Running Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install prerequisits
        run: sudo apt-get install -y python3 python3-pip
      - name: build the code
        run: cd CAN_messages &&  python3 signals.py
      - name: run tests
        run: echo "running tests"
