name: Build and Test "CAN_Messages" Component

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
#    name: Built the source code and run Tests(GoogleTest) 
    name: Running Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install prerequisits
        run: sudo apt-get install python3 python3-pip
      - name: build the code
        run: |
#          mkdir build 
#          cd build
#          cmake ../CAN_Messages
#          cmake --build .
            echo "running python code"
      - name: run tests
#        run: ./build/lib_ut_tests
        run: echo "running tests"
