name: Build and Test "File IO" Component

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    name: Built the source code and run Tests(GoogleTest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install prerequisits
        run: echo "Installing neccesary packages"
      - name: build the code
        run: echo "Building"
      - name: run tests
        run: echo "Testing"
