name: Build and Run "The complete project"

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_:
    name: Build and Run "The complete project"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install prerequisits
        run: sudo apt-get install -y python3 python3-pip cmake build-essential tree
      - name: visually control the code
        run: tree .
      - name: Build the Code
        run: |
          mkdir build 
          cd build
          cmake ..
          cmake --build .
      - name: Notify user
        run: echo "Success!"
